services:
  criatorio-postgres-db:
    image: postgres:16-alpine
    container_name: criatorio-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-docker}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-docker}
      POSTGRES_DB: ${DATABASE_NAME:-criatorio}
    ports:
      - '5432:5432'
    volumes:
      - criatorio_db_volume:/var/lib/postgresql/data
    networks:
      - criatorio-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME:-docker}"]
      interval: 10s
      timeout: 5s
      retries: 5

  criatorio-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: criatorio-api
    restart: unless-stopped
    ports:
      - '3366:3000'
      - '5555:5555'
    networks:
      - criatorio-network
    env_file:
      - .env
    depends_on:
      criatorio-postgres-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    

  criatorio-minio:
    container_name: criatorio-minio
    image: minio/minio:RELEASE.2025-02-03T21-03-04Z-cpuv1
    command: server /data --address ":9000" --console-address ":9001"
    restart: unless-stopped
    ports:
      - '9000:9000'   # API
      - '9001:9001'   # Console Web UI
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - criatorio_minio_data:/data
    networks:
      - criatorio-network
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s

volumes:
  criatorio_db_volume:
    driver: local
  criatorio_minio_data:
    driver: local

networks:
  criatorio-network:
    driver: bridge
